### ISSUE TITLE
Regex change required

### ISSUE THREAD

**Issue by JDI-Developers** [DeBoerTool/html-webpack-blade-plugin#7]
As indicated we found an issue with the tag replacement by the blade plugin when the 3D viewer code is mininified. When minified the Blade plugin completely replaces the code with `@extends('html')` this due to the * in the regex.

Current: https://regex101.com/r/0Be8yH/1
Changed: https://regex101.com/r/oztTGm/2

We've fixed this by adjusting <$ {tag}. *> to: <$ {tag}?>

**Comment by danielsdeboer** [comment]
Interesting. A few issues:

1) A Blade template doesn't benefit from minification since it's server side code. Blade can output minified HTML but that's the responsibility of the Blade compiler. HTML minification can be safely disabled here.
2) More critically, your regex fails on tags with attributes so making this change would introduce a regression for #4. 

That's not to say there's not a better regex to be had here, just the one you've provided is not that regex.

**Comment by danielsdeboer** [comment]
I've update the README to mention that minification isn't required and may in fact break the Blade compiler.

**Comment by danielsdeboer** [comment]
https://www.npmjs.com/package/html-webpack-blade-plugin/v/0.2.2
